"""One-off: rewrite snake_case artefact keys to camelCase.

Artifacts generated by the Python service between the port and the alias fix
were stored with snake_case keys. The frontend and the JavaScript
code-generation service both read camelCase, so those documents render as
"None specified" and generate code against no schema. This rewrites them in
place.

Read-modify-write on the artefact subtrees only; approval chains, history and
stages are not touched. Safe to run more than once — a document already in
camelCase is left alone.

    python scripts/migrate_artefacts_to_camel_case.py [--apply]

Without --apply it reports what it would change and writes nothing.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app import db  # noqa: E402

# The artefact subtrees agents produce. Everything else on the document is
# written by the state machine and was never snake_case.
ARTEFACT_FIELDS = ["content", "detailedReport", "ui", "teamReports", "workItems", "workItemIntegrity"]

# Only real snake_case identifiers are renamed. One stored artifact has a
# whole paragraph of leaked model output as a dict key, underscores included;
# "contains an underscore" would rewrite that too, for no gain and some risk.
_SNAKE = re.compile(r"^[a-z][a-z0-9]*(?:_[a-z0-9]+)+$")


def to_camel(key: str) -> str:
    head, *rest = key.split("_")
    return head + "".join(word.capitalize() for word in rest)


def convert(value):
    """Rename dict keys recursively; leave every value untouched."""
    if isinstance(value, dict):
        return {(to_camel(k) if _SNAKE.match(k) else k): convert(v) for k, v in value.items()}
    if isinstance(value, list):
        return [convert(v) for v in value]
    return value


def snake_keys(value, found=None):
    found = found if found is not None else []
    if isinstance(value, dict):
        for k, v in value.items():
            if _SNAKE.match(k):
                found.append(k)
            snake_keys(v, found)
    elif isinstance(value, list):
        for v in value:
            snake_keys(v, found)
    return found


def main(apply: bool) -> int:
    changed = 0
    for artifact in db.artifacts().find():
        update = {}
        renamed: list[str] = []
        for field in ARTEFACT_FIELDS:
            current = artifact.get(field)
            if current is None:
                continue
            converted = convert(current)
            if converted != current:
                update[field] = converted
                renamed += sorted(set(snake_keys(current)))

        if not update:
            continue

        changed += 1
        title = (artifact.get("title") or "")[:40]
        print(f"{artifact['_id']}  {title}")
        print(f"    fields: {', '.join(update)}")
        print(f"    keys  : {', '.join(sorted(set(renamed))[:10])}")

        if apply:
            db.artifacts().update_one({"_id": artifact["_id"]}, {"$set": update})

    print(f"\n{changed} artifact(s) {'migrated' if apply else 'would be migrated'}")
    if not apply and changed:
        print("Re-run with --apply to write the changes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(apply="--apply" in sys.argv))
